<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Real Estate Broker Form</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        .container {
            background-color: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            width: 100%;
            max-width: 600px;
        }
        h2 {
            text-align: center;
            color: #333;
        }
        .form-group {
            margin-bottom: 15px;
        }
        .form-group label {
            display: block;
            font-weight: bold;
        }
        .form-group input, .form-group select, .form-group textarea {
            width: 100%;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
        }
        .form-group textarea {
            height: 100px;
        }
        .submit-btn {
            background-color: #28a745;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            font-size: 16px;
            cursor: pointer;
            width: 100%;
        }
        .submit-btn:hover {
            background-color: #218838;
        }
    </style>
</head>
<body>

<div class="container">
    <h2>Real Estate Broker Form</h2>
    <form id="realEstateForm">
        <div class="form-group">
            <label for="firstName">First Name</label>
            <input type="text" id="firstName" name="firstName" required>
        </div>

        <div class="form-group">
            <label for="lastName">Last Name</label>
            <input type="text" id="lastName" name="lastName" required>
        </div>

        <div class="form-group">
            <label for="propertyType">Property Type</label>
            <select id="propertyType" name="propertyType" required>
                <option value="">Select Property Type</option>
                <option value="AgriLand">AgriLand</option>
                <option value="Plot">Plot</option>
                <option value="Residential Apartment">Residential Apartment</option>
                <option value="Commercial Block">Commercial Block</option>
            </select>
        </div>

        <div class="form-group">
            <label for="transactionType">Transaction Type</label>
            <select id="transactionType" name="transactionType" required>
                <option value="">Select Transaction Type</option>
                <option value="Sell">Sell</option>
                <option value="Purchase">Purchase</option>
                <option value="Rental">Rental</option>
                <option value="Lease">Lease</option>
            </select>
        </div>

        <div class="form-group">
            <label for="size">Size</label>
            <select id="size" name="size" required>
                <option value="">Select Size Unit</option>
                <option value="Acres">Acres</option>
                <option value="Sqft">Sqft</option>
            </select>
        </div>

        <div class="form-group">
            <label for="area">Area</label>
            <select id="area" name="area" required>
                <option value="">Select Area</option>
                <option value="Rural">Rural</option>
                <option value="Urban">Urban</option>
            </select>
        </div>

        <div class="form-group">
            <label for="price">Price</label>
            <input type="number" id="price" name="price" required>
        </div>

        <div class="form-group">
            <label for="location">Location</label>
            <input type="text" id="location" name="location" required>
        </div>

        <div class="form-group">
            <label for="description">Description</label>
            <textarea id="description" name="description" required></textarea>
        </div>

        <button type="submit" class="submit-btn">Submit</button>
    </form>
</div>

<script>
    document.getElementById("realEstateForm").addEventListener("submit", function (e) {
        e.preventDefault();
        const formData = new FormData(this);

        fetch("https://script.google.com/macros/s/AKfycbyS3DsUvIPZIU3SH6kxKd0pyawv1yj0MJkjB0x26k7SC6Mbj_-YP-Xp89ewFKi8_M2kYw/exec", {
            method: "POST",
            body: formData
        })
        .then(response => response.json())
        .then(data => {
            if (data.result === "success") {
                alert("Thank you! Your data has been submitted.");
            } else {
                alert("There was an error submitting the form.");
            }
        })
        .catch(error => {
            console.error("Error:", error);
            alert("There was an error submitting the form.");
        });
    });
</script>
			<script>
    document.getElementById("realEstateForm").addEventListener("submit", function (e) {
        e.preventDefault(); // Prevent page refresh
        const formData = new FormData(this);

        fetch("https://script.google.com/macros/s/AKfycbyS3DsUvIPZIU3SH6kxKd0pyawv1yj0MJkjB0x26k7SC6Mbj_-YP-Xp89ewFKi8_M2kYw/exec", { // Replace with your Google Apps Script Web App URL
            method: "POST",
            body: formData
        })
        .then(response => response.json())
        .then(data => {
            if (data.result === "success") {
                alert("Thank you! Your data has been submitted.");
                this.reset(); // Clear the form fields
            } else {
                alert("Error submitting form: " + data.message);
            }
        })
        .catch(error => {
            console.error("Error:", error);
            alert("There was an error submitting the form.");
        });
    });
</script>


</body>
</html>
